const options = {
	method: 'GET',
	headers: {
		'X-RapidAPI-Key': 'a6484e6bdfmsh10496159871666dp1ad53ejsn6573e8751929',
		'X-RapidAPI-Host': 'coinranking1.p.rapidapi.com'
	}
};

fetch('https://coinranking1.p.rapidapi.com/coins?referenceCurrencyUuid=yhjMzLPhuIDl&timePeriod=24h&tiers%5B0%5D=1&orderBy=marketCap&orderDirection=desc&limit=50&offset=0', options)
	.then(response => response.json())
	.then((response) => {
        console.log(response)
        name1.innerHTML = response.data.coins[0].name;
        symbol1.innerHTML = response.data.coins[0].symbol;
        price1.innerHTML = response.data.coins[0].price;
        const var1 = response.data.coins[0].change ;
        change1.innerHTML = response.data.coins[0].change;
        marketcap1.innerHTML = response.data.coins[0].marketCap;
        rank1.innerHTML = response.data.coins[0].rank;
        name2.innerHTML = response.data.coins[1].name;
        symbol2.innerHTML = response.data.coins[1].symbol;
        price2.innerHTML = response.data.coins[1].price;
        change2.innerHTML = response.data.coins[1].change;
        marketcap2.innerHTML = response.data.coins[1].marketCap;
        rank2.innerHTML = response.data.coins[1].rank;
        name3.innerHTML = response.data.coins[2].name;
        symbol3.innerHTML = response.data.coins[2].symbol;
        price3.innerHTML = response.data.coins[2].price;
        change3.innerHTML = response.data.coins[2].change;
        marketcap3.innerHTML = response.data.coins[2].marketCap;
        rank3.innerHTML = response.data.coins[2].rank;
        name4.innerHTML = response.data.coins[3].name;
        symbol4.innerHTML = response.data.coins[3].symbol;
        price4.innerHTML = response.data.coins[3].price;
        change4.innerHTML = response.data.coins[3].change;
        marketcap4.innerHTML = response.data.coins[3].marketCap;
        rank4.innerHTML = response.data.coins[3].rank;
        name5.innerHTML = response.data.coins[4].name;
        symbol5.innerHTML = response.data.coins[4].symbol;
        price5.innerHTML = response.data.coins[4].price;
        change5.innerHTML = response.data.coins[4].change;
        marketcap5.innerHTML = response.data.coins[4].marketCap;
        rank5.innerHTML = response.data.coins[4].rank;
        name6.innerHTML = response.data.coins[5].name;
        symbol6.innerHTML = response.data.coins[5].symbol;
        price6.innerHTML = response.data.coins[5].price;
        change6.innerHTML = response.data.coins[5].change;
        marketcap6.innerHTML = response.data.coins[5].marketCap;
        rank6.innerHTML = response.data.coins[5].rank;
        name7.innerHTML = response.data.coins[6].name;
        symbol7.innerHTML = response.data.coins[6].symbol;
        price7.innerHTML = response.data.coins[6].price;
        change7.innerHTML = response.data.coins[6].change;
        marketcap7.innerHTML = response.data.coins[6].marketCap;
        rank7.innerHTML = response.data.coins[6].rank;
        name8.innerHTML = response.data.coins[7].name;
        symbol8.innerHTML = response.data.coins[7].symbol;
        price8.innerHTML = response.data.coins[7].price;
        change8.innerHTML = response.data.coins[7].change;
        marketcap8.innerHTML = response.data.coins[7].marketCap;
        rank8.innerHTML = response.data.coins[7].rank;
        name9.innerHTML = response.data.coins[8].name;
        symbol9.innerHTML = response.data.coins[8].symbol;
        price9.innerHTML = response.data.coins[8].price;
        change9.innerHTML = response.data.coins[8].change;
        marketcap9.innerHTML = response.data.coins[8].marketCap;
        rank9.innerHTML = response.data.coins[8].rank;
        name10.innerHTML = response.data.coins[9].name;
        symbol10.innerHTML = response.data.coins[9].symbol;
        price10.innerHTML = response.data.coins[9].price;
        change10.innerHTML = response.data.coins[9].change;
        marketcap10.innerHTML = response.data.coins[9].marketCap;
        rank10.innerHTML = response.data.coins[9].rank;
        name11.innerHTML = response.data.coins[10].name;
        symbol11.innerHTML = response.data.coins[10].symbol;
        price11.innerHTML = response.data.coins[10].price;
        change11.innerHTML = response.data.coins[10].change;
        marketcap11.innerHTML = response.data.coins[10].marketCap;
        rank11.innerHTML = response.data.coins[10].rank;
        name12.innerHTML = response.data.coins[11].name;
        symbol12.innerHTML = response.data.coins[11].symbol;
        price12.innerHTML = response.data.coins[11].price;
        change12.innerHTML = response.data.coins[11].change;
        marketcap12.innerHTML = response.data.coins[11].marketCap;
        rank12.innerHTML = response.data.coins[11].rank;
        name13.innerHTML = response.data.coins[12].name;
        symbol13.innerHTML = response.data.coins[12].symbol;
        price13.innerHTML = response.data.coins[12].price;
        change13.innerHTML = response.data.coins[12].change;
        marketcap13.innerHTML = response.data.coins[12].marketCap;
        rank13.innerHTML = response.data.coins[12].rank;
        name14.innerHTML = response.data.coins[13].name;
        symbol14.innerHTML = response.data.coins[13].symbol;
        price14.innerHTML = response.data.coins[13].price;
        change14.innerHTML = response.data.coins[13].change;
        marketcap14.innerHTML = response.data.coins[13].marketCap;
        rank14.innerHTML = response.data.coins[13].rank;
        name15.innerHTML = response.data.coins[14].name;
        symbol15.innerHTML = response.data.coins[14].symbol;
        price15.innerHTML = response.data.coins[14].price;
        change15.innerHTML = response.data.coins[14].change;
        marketcap15.innerHTML = response.data.coins[14].marketCap;
        rank15.innerHTML = response.data.coins[14].rank;
        name16.innerHTML = response.data.coins[15].name;
        symbol16.innerHTML = response.data.coins[15].symbol;
        price16.innerHTML = response.data.coins[15].price;
        change16.innerHTML = response.data.coins[15].change;
        marketcap16.innerHTML = response.data.coins[15].marketCap;
        rank16.innerHTML = response.data.coins[15].rank;
        name17.innerHTML = response.data.coins[16].name;
        symbol17.innerHTML = response.data.coins[16].symbol;
        price17.innerHTML = response.data.coins[16].price;
        change17.innerHTML = response.data.coins[16].change;
        marketcap17.innerHTML = response.data.coins[16].marketCap;
        rank17.innerHTML = response.data.coins[16].rank;
        name18.innerHTML = response.data.coins[17].name;
        symbol18.innerHTML = response.data.coins[17].symbol;
        price18.innerHTML = response.data.coins[17].price;
        change18.innerHTML = response.data.coins[17].change;
        marketcap18.innerHTML = response.data.coins[17].marketCap;
        rank18.innerHTML = response.data.coins[17].rank;
        name19.innerHTML = response.data.coins[18].name;
        symbol19.innerHTML = response.data.coins[18].symbol;
        price19.innerHTML = response.data.coins[18].price;
        change19.innerHTML = response.data.coins[18].change;
        marketcap19.innerHTML = response.data.coins[18].marketCap;
        rank19.innerHTML = response.data.coins[18].rank;
        name20.innerHTML = response.data.coins[19].name;
        symbol20.innerHTML = response.data.coins[19].symbol;
        price20.innerHTML = response.data.coins[19].price;
        change20.innerHTML = response.data.coins[19].change;
        marketcap20.innerHTML = response.data.coins[19].marketCap;
        rank20.innerHTML = response.data.coins[19].rank;
    })
	.catch(err => console.error(err));

